package br.com.nasser.view;

import java.util.List;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

import br.com.nasser.model.DAO.BairroDAO;
import br.com.nasser.model.DAO.CidadeDAO;
import br.com.nasser.model.bo.Bairro;
import br.com.nasser.model.bo.Cidade;

/**
 *
 * @author house
 */
public class TelaCadEndereco extends javax.swing.JFrame {

	/**
	 * Creates new form FormModeloCadastros
	 */
	public TelaCadEndereco() {
		initComponents();
		carregarCombo();
	}

	public void carregarCombo() {

		CidadeDAO cidadeDAO = new CidadeDAO();
		List<Cidade> list = cidadeDAO.retrieve();
		for (Cidade item : list) {
			jComboBoxCidade.addItem(item.getDescricaoCidade());
		}

		BairroDAO bairroDAO = new BairroDAO();
		List<Bairro> bairroList = bairroDAO.retrieve();
		for (Bairro item : bairroList) {
			jComboBoxBairro.addItem(item.getDescricaoBairro());
		}

	}

	public JComboBox<String> getjComboBoxBairro() {
		return jComboBoxBairro;
	}

	public void setjComboBoxBairro(JComboBox<String> jComboBoxBairro) {
		this.jComboBoxBairro = jComboBoxBairro;
	}

	public JComboBox<String> getjComboBoxCidade() {
		return jComboBoxCidade;
	}

	public void setjComboBoxCidade(JComboBox<String> jComboBoxCidade) {
		this.jComboBoxCidade = jComboBoxCidade;
	}

	public JTextField getjTFCEP() {
		return jTFCEP;
	}

	public void setjTFCEP(JTextField jTFCEP) {
		this.jTFCEP = jTFCEP;
	}

	public JTextField getjTFLogradouro() {
		return jTFLogradouro;
	}

	public void setjTFLogradouro(JTextField jTFLogradouro) {
		this.jTFLogradouro = jTFLogradouro;
	}

	public JButton getjButtonBuscar() {
		return jButtonBuscar;
	}

	public void setjButtonBuscar(JButton jButtonBuscar) {
		this.jButtonBuscar = jButtonBuscar;
	}

	public JButton getjButtonCancelar() {
		return jButtonCancelar;
	}

	public void setjButtonCancelar(JButton jButtonCancelar) {
		this.jButtonCancelar = jButtonCancelar;
	}

	public JButton getjButtonGravar() {
		return jButtonGravar;
	}

	public void setjButtonGravar(JButton jButtonGravar) {
		this.jButtonGravar = jButtonGravar;
	}

	public JButton getjButtonNovo() {
		return jButtonNovo;
	}

	public void setjButtonNovo(JButton jButtonNovo) {
		this.jButtonNovo = jButtonNovo;
	}

	public JButton getjButtonSair() {
		return jButtonSair;
	}

	public void setjButtonSair(JButton jButtonSair) {
		this.jButtonSair = jButtonSair;
	}

	public JTextField getjTFIdEndereco() {
		return jTFIdEndereco;
	}

	public void setjTFIdEndereco(JTextField jTFIdEndereco) {
		this.jTFIdEndereco = jTFIdEndereco;
	}

	public JTextField getjTFNomeBairro() {
		return jTFCEP;
	}

	public void setjTFNomeBairro(JTextField TFNomeBairro) {
		this.jTFCEP = jTFCEP;
	}

	public JPanel getjPanelDados() {
		return jPanelDados;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelTitulo = new javax.swing.JPanel();
		jLabelTitulo = new javax.swing.JLabel();
		jPanelDados = new javax.swing.JPanel();
		jLId = new javax.swing.JLabel();
		jTFIdEndereco = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTFCEP = new javax.swing.JTextField();
		jComboBoxBairro = new javax.swing.JComboBox<>();
		jLId1 = new javax.swing.JLabel();
		jLId2 = new javax.swing.JLabel();
		jComboBoxCidade = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jTFLogradouro = new javax.swing.JTextField();
		jPanelBotoes = new javax.swing.JPanel();
		jButtonNovo = new javax.swing.JButton();
		jButtonCancelar = new javax.swing.JButton();
		jButtonGravar = new javax.swing.JButton();
		jButtonBuscar = new javax.swing.JButton();
		jButtonSair = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Cadastro de Bairro");
		setResizable(false);

		jPanelTitulo.setBackground(new java.awt.Color(204, 255, 0));
		jPanelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jPanelTitulo.setPreferredSize(new java.awt.Dimension(533, 75));

		jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		jLabelTitulo.setForeground(new java.awt.Color(51, 0, 153));
		jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTitulo.setText("Endereco");

		javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
		jPanelTitulo.setLayout(jPanelTituloLayout);
		jPanelTituloLayout
				.setHorizontalGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE));
		jPanelTituloLayout
				.setVerticalGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE));

		getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

		jPanelDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLId.setText("ID:");

		jTFIdEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		jTFIdEndereco.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTFIdEnderecoActionPerformed(evt);
			}
		});

		jLabel2.setText("CEP:");

		jTFCEP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTFCEPActionPerformed(evt);
			}
		});

		jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
		jComboBoxBairro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxBairroActionPerformed(evt);
			}
		});

		jLId1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLId1.setText("Cidade:");

		jLId2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLId2.setText("Bairro:");

		jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
		jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxCidadeActionPerformed(evt);
			}
		});

		jLabel3.setText("Logradouro:");

		jTFLogradouro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTFLogradouroActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanelDadosLayout = new javax.swing.GroupLayout(jPanelDados);
		jPanelDados.setLayout(jPanelDadosLayout);
		jPanelDadosLayout.setHorizontalGroup(jPanelDadosLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelDadosLayout.createSequentialGroup().addGroup(jPanelDadosLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanelDadosLayout.createSequentialGroup().addGap(20, 20, 20)
								.addGroup(jPanelDadosLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanelDadosLayout.createSequentialGroup().addComponent(jLId1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jComboBoxCidade, 0, 187, Short.MAX_VALUE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLId2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE,
														176, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanelDadosLayout.createSequentialGroup().addComponent(jLId)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTFIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(50, 50, 50)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jTFCEP))))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelDadosLayout.createSequentialGroup().addContainerGap()
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTFLogradouro)))
						.addGap(0, 0, 0)));
		jPanelDadosLayout.setVerticalGroup(jPanelDadosLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelDadosLayout.createSequentialGroup().addContainerGap().addGroup(jPanelDadosLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLId)
						.addComponent(jTFIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2).addComponent(jTFCEP, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLId1)
								.addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLId2)
								.addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(32, 32, 32)
						.addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTFLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addContainerGap(27, Short.MAX_VALUE)));

		getContentPane().add(jPanelDados, java.awt.BorderLayout.LINE_START);

		jPanelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jPanelBotoes.setPreferredSize(new java.awt.Dimension(533, 50));

		jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/New document.png"))); // NOI18N
		jButtonNovo.setText("Novo");
		jButtonNovo.setPreferredSize(new java.awt.Dimension(100, 30));
		jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonNovoActionPerformed(evt);
			}
		});
		jPanelBotoes.add(jButtonNovo);

		jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel.png"))); // NOI18N
		jButtonCancelar.setText("Cancelar");
		jButtonCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonCancelar);

		jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
		jButtonGravar.setText("Gravar");
		jButtonGravar.setEnabled(false);
		jButtonGravar.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonGravar);

		jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Find.png"))); // NOI18N
		jButtonBuscar.setText("Buscar");
		jButtonBuscar.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonBuscar);

		jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
		jButtonSair.setText("Sair");
		jButtonSair.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonSair);

		getContentPane().add(jPanelBotoes, java.awt.BorderLayout.SOUTH);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNovoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonNovoActionPerformed

	private void jComboBoxBairroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxBairroActionPerformed

	}// GEN-LAST:event_jComboBoxBairroActionPerformed

	private void jTFCEPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFCEPActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTFCEPActionPerformed

	private void jTFIdEnderecoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFIdEnderecoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTFIdEnderecoActionPerformed

	private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxCidadeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBoxCidadeActionPerformed

	private void jTFLogradouroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFLogradouroActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTFLogradouroActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ModeloCadastros.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ModeloCadastros().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonBuscar;
	private javax.swing.JButton jButtonCancelar;
	private javax.swing.JButton jButtonGravar;
	private javax.swing.JButton jButtonNovo;
	private javax.swing.JButton jButtonSair;
	private javax.swing.JComboBox<String> jComboBoxBairro;
	private javax.swing.JComboBox<String> jComboBoxCidade;
	private javax.swing.JLabel jLId;
	private javax.swing.JLabel jLId1;
	private javax.swing.JLabel jLId2;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabelTitulo;
	private javax.swing.JPanel jPanelBotoes;
	private javax.swing.JPanel jPanelDados;
	private javax.swing.JPanel jPanelTitulo;
	private javax.swing.JTextField jTFCEP;
	private javax.swing.JTextField jTFIdEndereco;
	private javax.swing.JTextField jTFLogradouro;
	// End of variables declaration//GEN-END:variables
}
