/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.nasser.view;

import java.util.List;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JTextField;

import br.com.nasser.model.DAO.FornecedorDAO;
import br.com.nasser.model.bo.Fornecedor;

/**
 *
 * @author house
 */
public class TelaCadFoneFornecedor extends javax.swing.JFrame {

	/**
	 * Creates new form FormModeloCadastros
	 */
	public TelaCadFoneFornecedor() {
		initComponents();
		carregarComboCNPJ();
	}

	public void carregarComboCNPJ() {

		FornecedorDAO fornecedorDAO = new FornecedorDAO();
		List<Fornecedor> list = fornecedorDAO.retrieve();
		for (Fornecedor item : list) {
			jComboBoxFornecedor.addItem(item.getCnpjFornecedor());
		}

	}

	public JComboBox<String> getjComboBoxFornecedor() {
		return jComboBoxFornecedor;
	}

	public void setjComboBoxFornecedor(JComboBox<String> jComboBoxFornecedor) {
		this.jComboBoxFornecedor = jComboBoxFornecedor;
	}

	public JButton getjButtonBuscar() {
		return jButtonBuscar;
	}

	public void setjButtonBuscar(JButton jButtonBuscar) {
		this.jButtonBuscar = jButtonBuscar;
	}

	public JButton getjButtonCancelar() {
		return jButtonCancelar;
	}

	public void setjButtonCancelar(JButton jButtonCancelar) {
		this.jButtonCancelar = jButtonCancelar;
	}

	public JButton getjButtonGravar() {
		return jButtonGravar;
	}

	public void setjButtonGravar(JButton jButtonGravar) {
		this.jButtonGravar = jButtonGravar;
	}

	public JButton getjButtonNovo() {
		return jButtonNovo;
	}

	public void setjButtonNovo(JButton jButtonNovo) {
		this.jButtonNovo = jButtonNovo;
	}

	public JButton getjButtonSair() {
		return jButtonSair;
	}

	public void setjButtonSair(JButton jButtonSair) {
		this.jButtonSair = jButtonSair;
	}

	public JTextField getjFormattedTextFieldFone() {
		return jFormattedTextFieldFone;
	}

	public void setjFormattedTextFieldFone(JFormattedTextField jFormattedTextFieldFone) {
		this.jFormattedTextFieldFone = jFormattedTextFieldFone;
	}

	public JPanel getjPanelDados() {
		return jPanelDados;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelTitulo = new javax.swing.JPanel();
		jLabelTitulo = new javax.swing.JLabel();
		jPanelDados = new javax.swing.JPanel();
		jLabelFone = new javax.swing.JLabel();
		jFormattedTextFieldFone = new javax.swing.JFormattedTextField();
		jComboBoxFornecedor = new javax.swing.JComboBox<>();
		jLabelFone1 = new javax.swing.JLabel();
		jPanelBotoes = new javax.swing.JPanel();
		jButtonNovo = new javax.swing.JButton();
		jButtonCancelar = new javax.swing.JButton();
		jButtonGravar = new javax.swing.JButton();
		jButtonBuscar = new javax.swing.JButton();
		jButtonSair = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Formulário de Cadastro de  Fone Fornecedor");
		setResizable(false);

		jPanelTitulo.setBackground(new java.awt.Color(204, 255, 0));
		jPanelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jPanelTitulo.setPreferredSize(new java.awt.Dimension(533, 75));

		jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		jLabelTitulo.setForeground(new java.awt.Color(51, 0, 153));
		jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTitulo.setText("Fone Fornecedor");

		javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
		jPanelTitulo.setLayout(jPanelTituloLayout);
		jPanelTituloLayout
				.setHorizontalGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE));
		jPanelTituloLayout
				.setVerticalGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE));

		getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

		jPanelDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabelFone.setText("Fone:");

		try {
			jFormattedTextFieldFone.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxFornecedorActionPerformed(evt);
			}
		});

		jLabelFone1.setText("CNPJ");

		javax.swing.GroupLayout jPanelDadosLayout = new javax.swing.GroupLayout(jPanelDados);
		jPanelDados.setLayout(jPanelDadosLayout);
		jPanelDadosLayout.setHorizontalGroup(jPanelDadosLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelDadosLayout.createSequentialGroup().addContainerGap()
						.addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jFormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, 195,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelFone))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
						.addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 292,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelFone1))
						.addContainerGap()));
		jPanelDadosLayout.setVerticalGroup(jPanelDadosLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelDadosLayout.createSequentialGroup().addGap(49, 49, 49)
						.addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelFone).addComponent(jLabelFone1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jFormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(103, Short.MAX_VALUE)));

		getContentPane().add(jPanelDados, java.awt.BorderLayout.CENTER);

		jPanelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jPanelBotoes.setPreferredSize(new java.awt.Dimension(533, 50));

		jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/New document.png"))); // NOI18N
		jButtonNovo.setText("Novo");
		jButtonNovo.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonNovo);

		jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel.png"))); // NOI18N
		jButtonCancelar.setText("Cancelar");
		jButtonCancelar.setEnabled(false);
		jButtonCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonCancelar);

		jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
		jButtonGravar.setText("Gravar");
		jButtonGravar.setEnabled(false);
		jButtonGravar.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonGravar);

		jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Find.png"))); // NOI18N
		jButtonBuscar.setText("Buscar");
		jButtonBuscar.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonBuscar);

		jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
		jButtonSair.setText("Sair");
		jButtonSair.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanelBotoes.add(jButtonSair);

		getContentPane().add(jPanelBotoes, java.awt.BorderLayout.SOUTH);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxFornecedorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBoxFornecedorActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaCadFoneFornecedor.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaCadFoneFornecedor.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaCadFoneFornecedor.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaCadFoneFornecedor.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaCadFoneFornecedor().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonBuscar;
	private javax.swing.JButton jButtonCancelar;
	private javax.swing.JButton jButtonGravar;
	private javax.swing.JButton jButtonNovo;
	private javax.swing.JButton jButtonSair;
	private javax.swing.JComboBox<String> jComboBoxFornecedor;
	private javax.swing.JFormattedTextField jFormattedTextFieldFone;
	private javax.swing.JLabel jLabelFone;
	private javax.swing.JLabel jLabelFone1;
	private javax.swing.JLabel jLabelTitulo;
	private javax.swing.JPanel jPanelBotoes;
	private javax.swing.JPanel jPanelDados;
	private javax.swing.JPanel jPanelTitulo;
	// End of variables declaration//GEN-END:variables

}
